<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" ignored="0" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="101" started-at="2019-10-01T14:48:10 IST" finished-at="2019-10-01T14:48:10 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="101" started-at="2019-10-01T14:48:10 IST" finished-at="2019-10-01T14:48:10 IST">
      <class name="extentReports.NewTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:extentReports.NewTest@62fdb4a6]" name="setUp" is-config="true" duration-ms="186" started-at="2019-10-01T14:48:09 IST" finished-at="2019-10-01T14:48:10 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="functionality2Test1()[pri:0, instance:extentReports.NewTest@62fdb4a6]" name="functionality2Test1" duration-ms="23" started-at="2019-10-01T14:48:10 IST" finished-at="2019-10-01T14:48:10 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- functionality2Test1 -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:extentReports.NewTest@62fdb4a6]" name="getResult" is-config="true" duration-ms="11" started-at="2019-10-01T14:48:10 IST" finished-at="2019-10-01T14:48:10 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=functionality2Test1 status=SUCCESS method=NewTest.functionality2Test1()[pri:0, instance:extentReports.NewTest@62fdb4a6] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="FAIL" signature="functionality2Test2()[pri:0, instance:extentReports.NewTest@62fdb4a6]" name="functionality2Test2" duration-ms="2" started-at="2019-10-01T14:48:10 IST" finished-at="2019-10-01T14:48:10 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Sakinala] but found [Krishna]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Sakinala] but found [Krishna]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at extentReports.NewTest.functionality2Test2(NewTest.java:30)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- functionality2Test2 -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:extentReports.NewTest@62fdb4a6]" name="getResult" is-config="true" duration-ms="12" started-at="2019-10-01T14:48:10 IST" finished-at="2019-10-01T14:48:10 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=functionality2Test2 status=FAILURE method=NewTest.functionality2Test2()[pri:0, instance:extentReports.NewTest@62fdb4a6] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="SKIP" signature="functionality2Test3()[pri:0, instance:extentReports.NewTest@62fdb4a6]" name="functionality2Test3" duration-ms="7" started-at="2019-10-01T14:48:10 IST" finished-at="2019-10-01T14:48:10 IST">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[This is my skipp metho]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: This is my skipp metho
at extentReports.NewTest.functionality2Test3(NewTest.java:40)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- functionality2Test3 -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:extentReports.NewTest@62fdb4a6]" name="getResult" is-config="true" duration-ms="3" started-at="2019-10-01T14:48:10 IST" finished-at="2019-10-01T14:48:10 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=functionality2Test3 status=SKIP method=NewTest.functionality2Test3()[pri:0, instance:extentReports.NewTest@62fdb4a6] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:extentReports.NewTest@62fdb4a6]" name="tearDown" is-config="true" duration-ms="553" started-at="2019-10-01T14:48:10 IST" finished-at="2019-10-01T14:48:10 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- extentReports.NewTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
