<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="24751" started-at="2020-01-30T16:18:49 IST" finished-at="2020-01-30T16:19:14 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="24751" started-at="2020-01-30T16:18:49 IST" finished-at="2020-01-30T16:19:14 IST">
      <class name="javaPractice.TC001">
        <test-method status="PASS" signature="setUp()[pri:0, instance:javaPractice.TC001@120d6fe6]" name="setUp" is-config="true" duration-ms="226" started-at="2020-01-30T16:18:49 IST" finished-at="2020-01-30T16:18:49 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="bf()[pri:0, instance:javaPractice.TC001@120d6fe6]" name="bf" is-config="true" duration-ms="2" started-at="2020-01-30T16:18:49 IST" finished-at="2020-01-30T16:18:49 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- bf -->
        <test-method status="FAIL" signature="TC_0001()[pri:0, instance:javaPractice.TC001@120d6fe6]" name="TC_0001" duration-ms="19345" started-at="2020-01-30T16:18:49 IST" finished-at="2020-01-30T16:19:08 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[did not expect to find [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: did not expect to find [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at javaPractice.TC001.TC_0001(TC001.java:36)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_0001 -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:javaPractice.TC001@120d6fe6]" name="getResult" is-config="true" duration-ms="2955" started-at="2020-01-30T16:19:08 IST" finished-at="2020-01-30T16:19:11 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=TC_0001 status=FAILURE method=TC001.TC_0001()[pri:0, instance:javaPractice.TC001@120d6fe6] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="PASS" signature="TearDown()[pri:0, instance:javaPractice.TC001@120d6fe6]" name="TearDown" is-config="true" duration-ms="2407" started-at="2020-01-30T16:19:11 IST" finished-at="2020-01-30T16:19:14 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
        <test-method status="PASS" signature="AfterTest()[pri:0, instance:javaPractice.TC001@120d6fe6]" name="AfterTest" is-config="true" duration-ms="1" started-at="2020-01-30T16:19:14 IST" finished-at="2020-01-30T16:19:14 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AfterTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:javaPractice.TC001@120d6fe6]" name="tearDown" is-config="true" duration-ms="682" started-at="2020-01-30T16:19:14 IST" finished-at="2020-01-30T16:19:15 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- javaPractice.TC001 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
